#! /bin/sh

### BEGIN INIT INFO
# Provides: bot-PiServer
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $named
# Default-Start:     2 3 4 5
# Default-Stop: 
# Short-Description: start bot server
# Description:
### END INIT INFO

#Activate
# sudo chmod 0755 /etc/init.d/bot-Server
# sudo update-rc.d bot-Server defaults

# Some things that run always
#su ADD HERE

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    su root -c 'sudo node /home/$USER/ubuntuBot/server/app/server.js'
    echo "Starting bot server"
    # Print the IP address
    _IP=$(hostname -I) || true
    if [ "$_IP" ]; then
      printf "My IP address is %s\n" "$_IP"
    fi
    ;;
  stop)
    su root -c 'sudo killall node'
    echo "bot server has been stopped (didn't double check though)"
    ;;
  *)
    echo "Usage: /etc/init.d/bot-Server {start|stop}"
    exit 1
    ;;
esac

exit 0
